name: Documentation Build
on:
  pull_request:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs-gen/**'
      - 'docs/**'
jobs:
  docs:
    name: Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            docs/node_modules
          key: ${{ runner.os }}-workspace-docs-${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DOCS_DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Generate API documentation
        run: ./docs-gen.sh
      - name: Build and deploy to staging
        run: ./deploy-staging.sh
